// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleStudentManagementSystem.Data;

#nullable disable

namespace SimpleStudentManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926220041_RestEntitiesAndRelationships")]
    partial class RestEntitiesAndRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimpleStudentManagementSystem.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CourseId");

                    b.ToTable("courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Credits = 40,
                            Description = "Fundamentals of C# and Object-Oriented Programming (OOP).",
                            Title = "C#"
                        },
                        new
                        {
                            CourseId = 2,
                            Credits = 15,
                            Description = "Data querying, filtering, and manipulation techniques.",
                            Title = "Linq"
                        },
                        new
                        {
                            CourseId = 3,
                            Credits = 25,
                            Description = "Database management, migrations, and relationship mapping.",
                            Title = "EFCore"
                        },
                        new
                        {
                            CourseId = 4,
                            Credits = 30,
                            Description = "Building structured web applications using Model-View-Controller.",
                            Title = "MVC"
                        },
                        new
                        {
                            CourseId = 5,
                            Credits = 35,
                            Description = "Building secure RESTful web services with ASP.NET Core.",
                            Title = "API"
                        });
                });

            modelBuilder.Entity("SimpleStudentManagementSystem.Entities.CourseInstructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("InstructorId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseInstructor");

                    b.HasData(
                        new
                        {
                            InstructorId = 1,
                            CourseId = 1
                        },
                        new
                        {
                            InstructorId = 2,
                            CourseId = 1
                        },
                        new
                        {
                            InstructorId = 2,
                            CourseId = 2
                        },
                        new
                        {
                            InstructorId = 3,
                            CourseId = 5
                        },
                        new
                        {
                            InstructorId = 4,
                            CourseId = 3
                        });
                });

            modelBuilder.Entity("SimpleStudentManagementSystem.Entities.Enrollment", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EnrollmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("Cast (GetDate() As date)");

                    b.Property<decimal?>("Grade")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            CourseId = 1,
                            EnrollmentDate = new DateOnly(1, 1, 1),
                            Grade = 90m
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 1,
                            EnrollmentDate = new DateOnly(1, 1, 1),
                            Grade = 85m
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 2,
                            EnrollmentDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            StudentId = 1,
                            CourseId = 4,
                            EnrollmentDate = new DateOnly(1, 1, 1),
                            Grade = 80m
                        },
                        new
                        {
                            StudentId = 5,
                            CourseId = 3,
                            EnrollmentDate = new DateOnly(1, 1, 1)
                        });
                });

            modelBuilder.Entity("SimpleStudentManagementSystem.Entities.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("InstructorId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            InstructorId = 1,
                            FullName = "Ahmed Hassan"
                        },
                        new
                        {
                            InstructorId = 2,
                            FullName = "Sarah Jenkins"
                        },
                        new
                        {
                            InstructorId = 3,
                            FullName = "Mahmoud Tarek"
                        },
                        new
                        {
                            InstructorId = 4,
                            FullName = "Elena Rostova"
                        },
                        new
                        {
                            InstructorId = 5,
                            FullName = "Omar Farouk"
                        });
                });

            modelBuilder.Entity("SimpleStudentManagementSystem.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("EnrollmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("Cast(GetDate() AS date)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StudentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Email = "youssef.karim@example.com",
                            EnrollmentDate = new DateOnly(1, 1, 1),
                            FullName = "Youssef Karim"
                        },
                        new
                        {
                            StudentId = 2,
                            DateOfBirth = new DateOnly(2003, 3, 15),
                            Email = "mariam.adel@example.com",
                            EnrollmentDate = new DateOnly(1, 1, 1),
                            FullName = "Mariam Adel"
                        },
                        new
                        {
                            StudentId = 3,
                            DateOfBirth = new DateOnly(2005, 7, 20),
                            Email = "liam.carter@example.com",
                            EnrollmentDate = new DateOnly(1, 1, 1),
                            FullName = "Liam Carter"
                        },
                        new
                        {
                            StudentId = 4,
                            DateOfBirth = new DateOnly(2006, 1, 12),
                            Email = "nour.eldin@example.com",
                            EnrollmentDate = new DateOnly(1, 1, 1),
                            FullName = "Nour El-Din"
                        },
                        new
                        {
                            StudentId = 5,
                            Email = "sofia.martinez@example.com",
                            EnrollmentDate = new DateOnly(1, 1, 1),
                            FullName = "Sofia Martinez"
                        });
                });

            modelBuilder.Entity("SimpleStudentManagementSystem.Entities.CourseInstructor", b =>
                {
                    b.HasOne("SimpleStudentManagementSystem.Entities.Course", "course")
                        .WithMany("instructors")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleStudentManagementSystem.Entities.Instructor", "instructor")
                        .WithMany("courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("course");

                    b.Navigation("instructor");
                });

            modelBuilder.Entity("SimpleStudentManagementSystem.Entities.Enrollment", b =>
                {
                    b.HasOne("SimpleStudentManagementSystem.Entities.Course", "course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleStudentManagementSystem.Entities.Student", "student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("course");

                    b.Navigation("student");
                });

            modelBuilder.Entity("SimpleStudentManagementSystem.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("instructors");
                });

            modelBuilder.Entity("SimpleStudentManagementSystem.Entities.Instructor", b =>
                {
                    b.Navigation("courses");
                });

            modelBuilder.Entity("SimpleStudentManagementSystem.Entities.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
